# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlMultiforward < Formula
  desc ""
  homepage "https://github.com/konstantinwirz"
  version "0.11.0"

  on_macos do
    url "https://github.com/konstantinwirz/kubectl-multiforward/releases/download/v0.11.0/kubectl-multiforward_Darwin_all.tar.gz"
    sha256 "796b5774752fb3a871fb18fbba5088ed83fa0e16d244b93da5eb069097ea39b3"

    def install
      bin.install "kubectl-multiforward"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/konstantinwirz/kubectl-multiforward/releases/download/v0.11.0/kubectl-multiforward_Linux_x86_64.tar.gz"
      sha256 "cfe9ea7ca6c1d0056b108de43fdc4672a2d3c79f5c8980f9d54efb3d91adef5b"
      def install
        bin.install "kubectl-multiforward"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/konstantinwirz/kubectl-multiforward/releases/download/v0.11.0/kubectl-multiforward_Linux_arm64.tar.gz"
      sha256 "f578bf690c871de76fcc69f05f36e433da8b3cb197d89ccbdd70dbc113d7fdc3"
      def install
        bin.install "kubectl-multiforward"
      end
    end
  end
end
